package com.computools.repository.table;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.Map;

@Setter
@NoArgsConstructor
@DynamoDBTable(tableName = "Configs")
public class Configs {
    @JsonProperty("config_id")
    private String configId;
    @JsonProperty("config_name")
    private String configName;
    @JsonProperty("output_config")
    private Map<String, String> outputConfig;
    @JsonProperty("input_config")
    private Map<String, String> inputConfig;
    @JsonProperty("owner")
    private String owner;

    public Configs(String configId) {
        this.configId = configId;
    }

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "config_id")
    public String getConfigId() {
        return configId;
    }

    @DynamoDBAttribute(attributeName = "config_name")
    public String getConfigName() {
        return configName;
    }

    @DynamoDBAttribute(attributeName = "output_config")
    public Map<String, String> getOutputConfig() {
        return outputConfig;
    }

    @DynamoDBAttribute(attributeName = "input_config")
    public Map<String, String> getInputConfig() {
        return inputConfig;
    }

    @DynamoDBAttribute(attributeName = "owner")
    public String getOwner() {
        return owner;
    }

    @Override
    public String toString() {
        return "Configs{" +
                "configId='" + configId + '\'' +
                ", configName='" + configName + '\'' +
                ", outputConfig=" + outputConfig +
                ", inputConfig=" + inputConfig +
                ", owner='" + owner + '\'' +
                '}';
    }
}
