package com.computools.repository.table;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.Map;

@Setter
@NoArgsConstructor
@DynamoDBTable(tableName = "Configurations")
public class Configurations {
    private Long tenantNo;

    private String configurationId;

    private String configurationName;

    private Map<String, String> configurationCredentials;

    private String accountType;

    private String credentialsType;

    public Configurations(Long tenantNo) {
        this.tenantNo = tenantNo;
    }
    public Configurations(Long tenantNo, String configurationId) {
        this.tenantNo = tenantNo;
        this.configurationId = configurationId;
    }
    @DynamoDBHashKey(attributeName = "tenantNo")
    public Long getTenantNo() {
        return tenantNo;
    }

    @DynamoDBAutoGeneratedKey
    @DynamoDBRangeKey(attributeName="configurationId")
    public String getConfigurationId() {
        return configurationId;
    }

    @DynamoDBAttribute(attributeName = "configurationName")
    public String getConfigurationName() {
        return configurationName;
    }

    @DynamoDBAttribute(attributeName = "configurationCredentials")
    public Map<String, String> getConfigurationCredentials() {
        return configurationCredentials;
    }

    @DynamoDBAttribute(attributeName = "accountType")
    public String getAccountType() {
        return accountType;
    }

    @DynamoDBAttribute(attributeName = "credentialsType")
    public String getCredentialsType() {
        return credentialsType;
    }

    @Override
    public String toString() {
        return "Configurations{" +
                "tenantNo=" + tenantNo +
                ", configurationId='" + configurationId + '\'' +
                ", configurationName='" + configurationName + '\'' +
                ", configurationCredentials=" + configurationCredentials +
                ", accountType=" + accountType +
                ", credentialsType=" + credentialsType +
                '}';
    }
}
