package com.computools.repository.table;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Setter
@NoArgsConstructor
@DynamoDBTable(tableName = "Logs")
public class Logs {
    @JsonProperty("agreement_id")
    private String agreementId;
    @JsonProperty("agreement_name")
    private String agreementName;
    @JsonProperty("user_agent")
    private String userAgent;

    public Logs(String agreementId) {
        this.agreementId = agreementId;
    }
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "agreement_id")
    public String getAgreementId() {
        return agreementId;
    }

    @DynamoDBAttribute(attributeName = "agreement_name")
    public String getAgreementName() {
        return agreementName;
    }

    @DynamoDBAttribute(attributeName = "user_agent")
    public String getUserAgent() {
        return userAgent;
    }

    @Override
    public String toString() {
        return "Logs{" +
                "agreementId='" + agreementId + '\'' +
                ", agreementName='" + agreementName + '\'' +
                ", userAgent='" + userAgent + '\'' +
                '}';
    }
}
