server:
  port: 8080
spring:
  application:
    name: jwt-token-security
acrobat:
  base_url: https://api.na4.adobesign.com/oauth/v2/
  base_api_url: https://api.na4.adobesign.com/api/rest/v6
  clientId: CBJCHBCAABAA0l_Y4o0uf4AHNk58s9y5uK2IRH_na9zZ
  clientSecret: x-11gqqcoU4p0zbDX2J0JXao1CtflGc_
  default_scopes: user_write:account, user_login:account, agreement_read:account, agreement_write:account, agreement_send:account
invoice_agent:
  user: AndriiPopov
  password: gwdwsqitaoqi
  base_url: https://computools.dev.spa-cloud.com/spa/service
amazon:
  access:
    key: test
    secret-key: test
  region: eu-central-1
  end-point:
    url: http://localhost:8000/
passwordKey: 900a07caf7d747ab386b4ad69e959baff3ded19156505bfd19ff43848a297ba4e4f7dee88beb38b71bd9acf59f87ad7ed37bfab5b12135e7cd8e3bc3a8853ef6a4215cb878d34a6857856b5f3fb3df6d
logging:
  level:
    ROOT: WARN
    org.springframework.security: WARN
    org.springframework.web: WARN
    com.amazonaws.*: WARN
    com.computools.*: DEBUG

