server:
  port: 8080
spring:
  application:
    name: jwt-token-security
acrobat:
  basePath: https://api.na4.adobesign.com/api/rest/v6
  clientId: CBJCHBCAABAA0l_Y4o0uf4AHNk58s9y5uK2IRH_na9zZ
  clientSecret: x-11gqqcoU4p0zbDX2J0JXao1CtflGc_
  default_scopes: user_write:account, user_login:account, agreement_read:account, agreement_write:account, agreement_send:account
amazon:
  access:
    key: test
    secret-key: test
  region: eu-central-1
  end-point:
    url: http://localhost:8000/
logging:
  level:
    ROOT: WARN
    org.springframework.security: WARN
    com.amazonaws.*: DEBUG
    com.computools.*: DEBUG

